#!/usr/bin/sh

# Command line arguments
menu_cmd=$1
editor_cmd=$2

# My scripts directory
scripts="$HOME/.scripts/"

# Use $MENU_CMD to choose a file from the scripts directory
cd $scripts
choice=`fd -tx | cut -c 3- | $menu_cmd 'Edit script: '`

# If something is chosen (ESC not pressed), then edit it
[ -z $choice ] || $editor_cmd "${scripts}${choice}"
